name: Assign Bot

on:
  issue_comment:
    types: [created]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
    - name: Check for "bot/assign"
      if: ${{ contains(toLower(github.event.comment.body), 'bot/assign') }}
      run: echo "Assigning issue to the comment author"

    - name: Assign the issue
      if: ${{ contains(toLower(github.event.comment.body), 'bot/assign') }}
      uses: kentaro-m/auto-assign@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        assignees: ${{ github.event.comment.user.login }}
