name: Assign Bot

on:
  issue_comment:
    types: [created]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
    - name: Assign the issue if comment is "bot/assign"
      if: ${{ github.event.comment.body == 'bot/assign' || github.event.comment.body == 'BOT/ASSIGN' }}
      uses: actions-ecosystem/action-assign@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        assignees: ${{ github.event.comment.user.login }}
